// <auto-generated />
namespace NMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class passwordfixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(passwordfixed));
        
        string IMigrationMetadata.Id
        {
            get { return "202007090836273_password-fixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
